[package]
name = "cache-locality"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
progress-observer = "3.0.0"
rand = "0.8.5"
rayon = "1.9.0"
